### ISSUE TITLE
Add Archidekt to !diff 

### ISSUE THREAD

**Issue by hexedsilicon** [theneosloth/Bolas#16]
Since https://archidekt.com/ is becoming very popular with the EDH crowd, would be nice to have !diff accept lists from there as well

**Comment by theneosloth** [comment]
Unfortunately Archidekt doesn't seem to provide any sort of an API or a direct link for the deck exports, so I don't think there is currently a way to support it with the diff command

**Comment by theneosloth** [comment]
Implemented in https://github.com/theneosloth/Bolas/pull/31
