### ISSUE TITLE
!price is not working

### ISSUE THREAD

**Issue by bmbowdish** [theneosloth/Bolas#19]
![Screen Shot 2019-05-15 at 4 48 54 PM](https://user-images.githubusercontent.com/15185628/57808436-5aae8380-7731-11e9-89ab-e8da50837166.png)

**Comment by shikexue** [comment]
Looks like scryfall changed their API: https://scryfall.com/blog/category/api

**Comment by theneosloth** [comment]
Fixed in fdf22d5b4f80e44e29b061e9d7dad07a3ada8b34
