### ISSUE TITLE
Duplicate reporting when cannot find card in multi-request message.

### ISSUE THREAD

**Issue by AranMason** [theneosloth/Bolas#25]
![image](https://user-images.githubusercontent.com/7109835/59068521-6f350480-8908-11e9-8dee-a071f3ad4b38.png)
![image](https://user-images.githubusercontent.com/7109835/59068540-79570300-8908-11e9-9b1b-20d439ef8400.png)
![image](https://user-images.githubusercontent.com/7109835/59068549-8542c500-8908-11e9-9d0d-9ae48a953765.png)

**Comment by theneosloth** [comment]
Should be fixed in 3f7fb8d0f7d1fe49dfc36def60c857e751906929
