### ISSUE TITLE
Art calls on a specific set doesnt pull the correct artwork

### ISSUE THREAD

**Issue by hexedsilicon** [theneosloth/Bolas#26]
How to reproduce:

`!art [[aven mindcensor e:mp2]]` should pull the art from the invocation, it instead shows the newest art (amonkhet) and shows the mp2 card as the card embed

**Comment by theneosloth** [comment]
Fixed in 8bb3a21fbd805485c4c99ac001c13b789935045a.

One notable change is that putting brackets around the card will trigger the command and the card fetcher at the same time, so in order to just get the image the command would be: `!art aven mindcensor e:mp2`
