### ISSUE TITLE
Online only promos !art/image doesn't work

### ISSUE THREAD

**Issue by hexedsilicon** [theneosloth/Bolas#3]
I'm trying to pull the art of some online only promos, such as [this one](https://scryfall.com/card/prm/65648)

I've tried artist tag, promo tag, and is:promo such as 
`!art [[stasis a:seb]]`
which pulls a very different art.

**Comment by theneosloth** [comment]
Bolas is currently blocked from pulling up online only cards because they caused issues with some of the other commands. It's a rather hacky way to solve that problem so I'll try to see if I can find a better solution sometime this week

**Comment by theneosloth** [comment]
Fixed for #5
