### ISSUE TITLE
!price functionality regarding foil cards / cards with latest digital releases

### ISSUE THREAD

**Issue by MelffyBunilla** [theneosloth/Bolas#37]
Hi theneosloth

I really appreciate your work with the Bolas bot, as it works really well with queries, and allows fast searches for the cards related to terms, especially for commander brewers like me. We're using it on the r/EDH discord, and there I've noticed two things, specifically regarding the !price command:

The !price command doesn't function well for two types of cards:
1. Cards that only exist in foil (Tymna, the Weaver) [The "usd" in the scryfall api does not contain foil prices, also not for those that only exist in foil.]
2. Cards where the latest release is digital (The Tabernacle at Pendrell Vale) [The scryfall api grabs the digital version for some reason, no matter if you use fuzzy or search.]

For the first one, it would probably just be a matter of also displaying the "usd_foil" price. (And while we're at it, you might as well also show the "eur" price.) 

For the second one, this likely needs some rework of the price functionality, but you already used similar methods for the !art command:
- Instead of using the "named" function, use the "search" function, but add a "order:usd" in the beginning of the query (so "q=order:usd [args]"), to filter out digital cards (you would normally use "not:digital", but if someone wants to know the tix price, it wouldn't be optimal).

What happens here is the following in the possible scenarios:
- Someone types in "Blood", you still return "too many cards match the search..."
- Someone types in "Blood Pet", it returns the lowest USD price (usd:0.24, usd_foil:none, eur:0.09, tix:none)
- Someone types in "Blood Pet set:7ed", it returns the price of that version
- Someone types in "Blood Pet order:tix", it overwrites your "order=usd", as providing two times "order" in a query it just selects the last one that is in the query, thus it provides the lowest TIX price
- Someone types in "Tymna, the Weaver", it returns the price of the foil card, and not the digital card, despite both having usd:none, the scryfall API seems to know what you want here, which is good!

Kind regards
LordBunilla

**Comment by theneosloth** [comment]
I've changed the price command so it displays every price scryfall provides (so it should add eur and usd_foil), and I've made adjustments to the query so it uses the order argument as you suggest.  I have all the changes done on the [price-fix](https://github.com/theneosloth/Bolas/tree/price-fix) branch, and I'll push it to the bot later today after I make sure that it doesn't break anything.

Thank you for providing such a detailed suggestion on how to improve Bolas! I'm glad he's still seeing use

**Comment by MelffyBunilla** [comment]
Sweet, thank you!

**Comment by MelffyBunilla** [comment]
How long does it usually take to see the effect on the discord?

**Comment by theneosloth** [comment]
The changes should now be available on the main bot instance.

**Comment by MelffyBunilla** [comment]
This change now somehow disabled the function that when you have "too many" cards in the [[ ]] command, that it just gives you the query list, instead of the entire list. This causes either a giant list to show up or doesn't answer at all (probably because the response exceeds 2000 characters).

**Comment by theneosloth** [comment]
Should be fixed now, left in a typo in the last commit

**Comment by MelffyBunilla** [comment]
Thank you! Works great now!
