### ISSUE TITLE
Weird and unexpected/wrong search results for single word name

### ISSUE THREAD

**Issue by hexedsilicon** [theneosloth/Bolas#7]
Searching for [[gix]] only brings up the card called Gix, rather than all cards with gix in the title, of which there are 4 as seen here. https://scryfall.com/search?q=gix

**Comment by hexedsilicon** [comment]
[[gix]] seems to only bring up the vanguard card, rather than the other cards for some reason

**Comment by theneosloth** [comment]
This is an intended behavior, Bolas brings up an exact match of the card if it exists. Vanguard cards can be excluded with a query like ``gix not:vanguard``

**Comment by theneosloth** [comment]
Behavior changed in #8 .  Cards like vanguards now require additional queries, queries like "gix" now return regular magic cards
